/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defensesystem.view.defences;

/**
 *
 * @author senukab
 */

import defensesystem.util.Event;
import defensesystem.util.Observer;
import defensesystem.view.controller.MainControllerForm;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import java.awt.Image;


public class HelicopterDefense extends BaseDefenseForm{
    /**
     * Creates new form BaseDefenseForm
     */
    public HelicopterDefense(String title, MainControllerForm mainController) {
        
        super(title, mainController);
        
        initComponents();
        setupGif();
        setTitle(title);
        
   

    }
    
    public void update(Event event) {
        super.update(event);
        
        if (event.getPosition() != -1) {
            int position = event.getPosition();
            
            if (position >= 20) {
                shootButton.setEnabled(true);
            } else {
                shootButton.setEnabled(false);
            }
            
            if (position >= 60) {
                missileOpButton.setEnabled(true);
            } else {
                missileOpButton.setEnabled(false);
            }
            
            if (position >= 80) {
                lasarButton.setEnabled(true);
            } else {
                lasarButton.setEnabled(false);
            }
        
        }
    }
    
    
    private void setupGif() {
        ImageIcon imageIcon = new ImageIcon(
                new ImageIcon(getClass().getResource("/defensesystem/view/defences/assets/helicopter.gif"))
                .getImage()
                .getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_FAST)
        );
        
        imageLabel.setIcon(imageIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        shootButton = new javax.swing.JButton();
        missileOpButton = new javax.swing.JButton();
        lasarButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Helicopter");
        setBackground(new java.awt.Color(48, 48, 48));
        setForeground(java.awt.Color.pink);

        shootButton.setBackground(new java.awt.Color(255, 102, 102));
        shootButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        shootButton.setForeground(new java.awt.Color(255, 255, 255));
        shootButton.setText("Shoot");
        shootButton.setEnabled(false);

        missileOpButton.setBackground(new java.awt.Color(255, 102, 102));
        missileOpButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        missileOpButton.setForeground(new java.awt.Color(255, 255, 255));
        missileOpButton.setText("Missile Operation");
        missileOpButton.setEnabled(false);

        lasarButton.setBackground(new java.awt.Color(255, 102, 102));
        lasarButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lasarButton.setForeground(new java.awt.Color(255, 255, 255));
        lasarButton.setText("Laser Operation");
        lasarButton.setEnabled(false);

        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(shootButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(missileOpButton))
                    .addComponent(lasarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(missileOpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lasarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatDark look and feel */
        
        try {
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatDarkLaf");
        }
        catch (Exception e) {
             System.err.println("Failed to initialize FlatLaf.");
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new HelicopterDefense("Helicopter", null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lasarButton;
    private javax.swing.JButton missileOpButton;
    private javax.swing.JButton shootButton;
    // End of variables declaration//GEN-END:variables
}
