/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defensesystem.view.defences;

/**
 *
 * @author senukab
 */

import defensesystem.util.Event;
import defensesystem.util.Observer;
import defensesystem.view.controller.MainControllerForm;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import java.awt.Image;


public class SubmarineDefense extends BaseDefenseForm {

    /**
     * Creates new form BaseDefenseForm
     */
    public SubmarineDefense(String title, MainControllerForm mainController) {
        
        super(title, mainController);
        
        initComponents();
        setupGif();
        setTitle(title);
        


    }
    
    public void update(Event event) {
        super.update(event);
        
        if (event.getPosition() != -1) {
            int position = event.getPosition();
            
            if (position >= 20) {
                shootButton.setEnabled(true);
            } else {
                shootButton.setEnabled(false);
            }
            
            if (position >= 40) {
                sonarOpButton.setEnabled(true);
            } else {
                sonarOpButton.setEnabled(false);
            }
            
            if (position >= 60) {
                tomahawkMissileButton.setEnabled(true);
            } else {
                tomahawkMissileButton.setEnabled(false);
            }
            
            if (position >= 80) {
                tridentMissileButton.setEnabled(true);
            } else {
                tridentMissileButton.setEnabled(false);
            }
        
        }
    }
    
    private void setupGif() {
        ImageIcon imageIcon = new ImageIcon(
                new ImageIcon(getClass().getResource("/defensesystem/view/defences/assets/submarine.gif"))
                .getImage()
                .getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_FAST)
        );
        
        imageLabel.setIcon(imageIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        shootButton = new javax.swing.JButton();
        tridentMissileButton = new javax.swing.JButton();
        sonarOpButton = new javax.swing.JButton();
        tomahawkMissileButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        positionSlider2 = new javax.swing.JSlider();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(48, 48, 48));
        setForeground(java.awt.Color.pink);

        shootButton.setBackground(new java.awt.Color(255, 102, 102));
        shootButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        shootButton.setForeground(new java.awt.Color(255, 255, 255));
        shootButton.setText("Shoot");
        shootButton.setEnabled(false);

        tridentMissileButton.setBackground(new java.awt.Color(255, 102, 102));
        tridentMissileButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        tridentMissileButton.setForeground(new java.awt.Color(255, 255, 255));
        tridentMissileButton.setText("Trident 2 Missile");
        tridentMissileButton.setEnabled(false);

        sonarOpButton.setBackground(new java.awt.Color(255, 102, 102));
        sonarOpButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        sonarOpButton.setForeground(new java.awt.Color(255, 255, 255));
        sonarOpButton.setText("Sonar Operation");
        sonarOpButton.setEnabled(false);

        tomahawkMissileButton.setBackground(new java.awt.Color(255, 102, 102));
        tomahawkMissileButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        tomahawkMissileButton.setForeground(new java.awt.Color(255, 255, 255));
        tomahawkMissileButton.setText("Tomahawk Missiles");
        tomahawkMissileButton.setEnabled(false);

        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shootButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tomahawkMissileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tridentMissileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(sonarOpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(sonarOpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tomahawkMissileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(tridentMissileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        positionSlider2.setMajorTickSpacing(20);
        positionSlider2.setOrientation(javax.swing.JSlider.VERTICAL);
        positionSlider2.setPaintLabels(true);
        positionSlider2.setPaintTicks(true);
        positionSlider2.setSnapToTicks(true);
        positionSlider2.setValue(0);

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 153));
        jLabel11.setText("Oxygen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(positionSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(positionSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatDark look and feel */
        
        try {
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatDarkLaf");
        }
        catch (Exception e) {
             System.err.println("Failed to initialize FlatLaf.");
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new SubmarineDefense("Submarine", null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider positionSlider2;
    private javax.swing.JButton shootButton;
    private javax.swing.JButton sonarOpButton;
    private javax.swing.JButton tomahawkMissileButton;
    private javax.swing.JButton tridentMissileButton;
    // End of variables declaration//GEN-END:variables
}
